name: Automated Linting

on: pull_request

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout Repository para baixar o cÃ³digo do projeto
        uses: actions/checkout@v4

      - name: âš™ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: ğŸ“¦ Install Dependencies com CI (Clean Install), instala exatamente o package-lock.json
        run: npm ci

      - name: Run Prettier
        run: npm run lint:prettier:check
  eslint:
    name: Eslint
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout Repository para baixar o cÃ³digo do projeto
        uses: actions/checkout@v4

      - name: âš™ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: ğŸ“¦ Install Dependencies com CI (Clean Install), instala exatamente o package-lock.json
        run: npm ci

      - name: Run Eslint
        run: npm run lint:eslint:check
  commitlint:
    name: CommitLint
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout Repository para baixar o cÃ³digo do projeto
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: âš™ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: ğŸ“¦ Install Dependencies com CI (Clean Install), instala exatamente o package-lock.json
        run: npm ci

      - name: Run Eslint
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
