name: Automated Tests

on: pull_request

jobs:
  jest:
    name: Jest Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout Repository para baixar o cÃ³digo do projeto
        uses: actions/checkout@v4

      - name: âš™ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: ğŸ“¦ Install Dependencies com CI (Clean Install), instala exatamente o package-lock.json
        run: npm ci

      - name: ğŸ§ª Run Tests
        run: npm test
